### ISSUE TITLE
Resolving memory leak using asyncAction

### ISSUE THREAD

**Issue by zyrolasting** [mobxjs/mobx-utils#71] opened 2017-08-07 22:19 UTC
New to mobx-utils, so I suspect this is more a question for clarification than an issue report. Please direct me accordingly and thanks in advance for any help.

What I want to do is use a store that I can refresh when I know new service data is available like `lazyObservable`, but easily attach more computed values and action functions. The endgame is to have a method for writing stores that's easy to teach to my team.

Starting from create-react-app, install the shown dependencies and use this app script.

    import React from 'react';
    import ReactDOM from 'react-dom';
    import {action, computed, extendObservable, observable} from 'mobx';
    import {observer} from 'mobx-react';
    import {asyncAction} from 'mobx-utils';

    const flipACoin = () => Math.random() > 0.5;

    function determineGodliness() {
      const screwYourRAM = new Array(1000000).fill(Math.random());

      return new Promise((resolve) => {
        setTimeout(() => {
          resolve([flipACoin(), flipACoin()]);
        }, 1500);
      });
    }

    function godStore() {
      const store = observable({
        alpha: false,
        omega: false,
        waiting: false,
        refresh: asyncAction(function *() {
          this.waiting = true;
          [this.alpha, this.omega] = yield determineGodliness();
          this.waiting = false;
        }),
        get isGod() {
          return this.alpha && this.omega;
        }
      });

      store.refresh();

      return store;
    }

    window.store = godStore();

    const App = observer(({store}) => <p>{
      (store.waiting)
        ? 'The suspense is killing me!'
        : (store.isGod)
          ? 'I am the Alpha and the Omega'
          : 'I just work here.'
    }</p>);

    ReactDOM.render(<App store={window.store} />, document.getElementById('root'));

Task manager shows memory usage increase every time you run `window.store.refresh()` in the console. Interestingly enough, using `setInterval(window.store.refresh, 3000)` actually causes oscillation in memory usage instead of a linear climb.

What can I do to be sure `screwYourRAM` will get garbage collected? All I care about keeping is what's returned from the generator, not what was allocated in the interim.

**Comment by mweststrate** [comment] 2017-08-31 11:34
Closing as duplicate of https://stackoverflow.com/questions/45556604/how-does-garbage-collection-address-async-actions-in-mobx-utils

**Closed by mweststrate** 2017-08-31 11:34 UTC
